import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import crypto from "node:crypto";
const BUS_DIR = path.join(os.homedir(), ".kitt", "household");
export type CommSource = "gmail" | "imessage" | "calendar" | "voice";
export interface CommMessage { id: string; source: CommSource; entity: string; from: string; subject: string; body: string; date: string; msgId: string; read: boolean; needsReply: boolean; createdAt: string; }
export interface TodoItem { id: string; title: string; notes?: string; dueHint?: string; priority: "low" | "medium" | "high"; entity: string; source: string; done: boolean; doneAt?: string; createdAt: string; }
async function readJson<T>(filename: string): Promise<T[]> { try { const text = await fs.readFile(path.join(BUS_DIR, filename), "utf-8"); return JSON.parse(text) as T[]; } catch { return []; } }
async function writeJson(filename: string, data: unknown): Promise<void> { await fs.mkdir(BUS_DIR, { recursive: true }); await fs.writeFile(path.join(BUS_DIR, filename), JSON.stringify(data, null, 2)); }
export async function postCommMessage(msg: Omit<CommMessage, "id" | "createdAt">): Promise<CommMessage> { const messages = await readJson<CommMessage>("comms-messages.json"); if (messages.some(m => m.msgId === msg.msgId)) { return messages.find(m => m.msgId === msg.msgId)!; } const newMsg: CommMessage = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), ...msg }; messages.push(newMsg); await writeJson("comms-messages.json", messages.slice(-500)); return newMsg; }
export async function getUnreadMessages(entity?: string): Promise<CommMessage[]> { const messages = await readJson<CommMessage>("comms-messages.json"); return messages.filter(m => !m.read && (!entity || m.entity === entity)); }
export async function getRecentMessages(hours = 24, entity?: string): Promise<CommMessage[]> { const messages = await readJson<CommMessage>("comms-messages.json"); const cutoff = new Date(Date.now() - hours * 60 * 60 * 1000).toISOString(); return messages.filter(m => m.createdAt > cutoff && (!entity || m.entity === entity)); }
export async function markCommRead(id: string): Promise<void> { const messages = await readJson<CommMessage>("comms-messages.json"); const target = messages.find(m => m.id === id); if (target) target.read = true; await writeJson("comms-messages.json", messages); }
export async function addTodo(todo: Omit<TodoItem, "id">): Promise<TodoItem> { const todos = await readJson<TodoItem>("todos.json"); const existing = todos.find(t => !t.done && t.title === todo.title && t.entity === todo.entity); if (existing) return existing; const newTodo: TodoItem = { id: crypto.randomUUID(), ...todo }; todos.push(newTodo); await writeJson("todos.json", todos); return newTodo; }
export async function getOpenTodos(entity?: string): Promise<TodoItem[]> { const todos = await readJson<TodoItem>("todos.json"); return todos.filter(t => !t.done && (!entity || t.entity === entity)); }
export async function getCommsSummary() { const [messages, todos] = await Promise.all([readJson<CommMessage>("comms-messages.json"), readJson<TodoItem>("todos.json")]); const last24h = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(); return { totalMessages: messages.length, unreadMessages: messages.filter(m => !m.read).length, needsReply: messages.filter(m => m.needsReply && !m.read).length, recent24h: messages.filter(m => m.createdAt > last24h).length, openTodos: todos.filter(t => !t.done).length, highPrioTodos: todos.filter(t => !t.done && t.priority === "high").length }; }
